title: 🪩

tabs:
  pages:
    label: Pages
    sections:
      listedPages:
        type: pages
        headline: listed
        status: listed
        create: default
        image: icon

      unlistedPages:
        type: pages
        headline: unlisted
        status: unlisted
        create: default
        image: icon

  # program:
  #   label: Program
  #   sections:
  #     events: sections/events

  # settings tab
  settings:
    label: Settings
    sections:
      appearance:
        type: fields
        fields:
          title:
            label: Site Title
            type: text
            icon: title

          titleDisplay:
            label: Display Title
            type: text
            icon: title
            width: 1/2

          subtitle:
            label: Subtitle
            type: text
            icon: title
            width: 1/2

          email:
            label: Contact Email
            type: email

          acknowledgement:
            label: Acknowledgement of Country
            type: writer

          seo:
            type: headline
            label: SEO

          metaDescription:
            label: Meta Description
            type: writer

          metaKeywords:
            label: Meta Keywords
            type: writer

  media:
    label: files
    sections:
      ae_logo:
        label: AE logos
        type: files
        template: ae_logo

      ae_logo_home:
        label: AE home logos
        type: files
        template: ae_logo_home

      audio_intro:
        type: files
        label: Audio Introduction
        template: audio_intro
        multiple: true
        help: Audio introduction to the festival.

      audio_intro_text:
        type: fields
        fields:
          audio_intro_text:
            label: Audio Introduction Text
            type: writer
            help: Text to accompany the audio introduction.

      audio_custom:
        label: Custom Audio (letter sounds)
        type: files
        template: audio_custom
        layout: table
        image:
          icon: audio
        columns:
          title: false
          audio_category:
            label: letter
        help: '"A!" "E?"'
