# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Deploy to CPanel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ***REMOVED***
          username: ***REMOVED***
          key: ${{ secrets.A_T_COM_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.A_T_COM_SSH_PRIVATE_KEY_PASSPHRASE }}
          port: 22
          debug: true
          script: cd public_html/Audible-Edge && git pull https://alexrturner:${{ secrets.A_T_COM_GITHUB_ACCESS_TOKEN }}@github.com/alexrturner/Audible-Edge.git
